<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
    <ProjectReference Include="..\Messages.Kafka\Messages.Kafka.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Foundation.EventBus.Rabbit" Version="1.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.App" Version="10.0.9"/>
    <PackageReference Include="Foundation.DependencyInjection.Web" Version="1.0.0" />
  </ItemGroup>

</Project>
