<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Confluent.Kafka" Version="2.15.0" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Microsoft.Extensions.Logging.Abstractions">
        <HintPath>..\..\..\..\..\..\Users\burne\.dotnet\shared\Microsoft.AspNetCore.App\10.0.3\Microsoft.Extensions.Logging.Abstractions.dll</HintPath>
      </Reference>
      <Reference Include="Microsoft.Extensions.Options">
        <HintPath>..\..\..\..\..\..\Users\burne\.dotnet\shared\Microsoft.AspNetCore.App\10.0.3\Microsoft.Extensions.Options.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Messages.Abstractions\Messages.Abstractions.csproj" />
    </ItemGroup>

</Project>
